biocommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("__reload__/", include("django_browser_reload.urls")),
    path('admin/', admin.site.urls),
    path('', include('products.urls', namespace='products')), 
    path('cart/', include('cart.urls', namespace='cart')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from .views import cart_add, cart_detail, cart_remove

app_name = 'cart'
urlpatterns = [
    path('add/<str:product_id>/', cart_add, name='cart_add'),
    path('', cart_detail, name='cart_detail'),
    path('remove/<str:product_id>/', cart_remove, name='cart_remove'),
]

products/urls.py
from django.urls import path
from . import views

app_name = "products"

urlpatterns = [
    path('', views.landing_page, name="landing_page"),
    path('products/', views.product_list, name="product_list"),
    path('products/<slug:category_slug>', views.product_list, name="product_list_by_category"),
    path('product/<str:id>/', views.product_detail, name="product_detail")
]

cart/models.py
from django.db import models
from products.models import Producto
class Cart(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    
    def get_total_price(self):
        return sum(item.get_total_price() for item in self.items.all())

class CartItem(models.Model):
    cart = models.ForeignKey(Cart, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Producto, related_name='cart_items', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    
    def get_total_price(self):
        return self.product.PROD_PRECIO_PUB * self.quantity
    

products/models.py
from django.db import models
from django.urls import reverse
# Create your models here


class Categoria(models.Model):
    CAT_NOMBRE = models.CharField(max_length=50)
    CAT_SLUG = models.SlugField(default="", null=False, unique=True)

    class Meta:
        verbose_name_plural = "categorias"

    def __str__(self):
        return self.CAT_NOMBRE
    
class Producto(models.Model):
    ID_PRODUCTO = models.CharField(primary_key=True, max_length=50)
    PROD_CATEGORIA = models.ForeignKey(Categoria, related_name="productos", on_delete=models.CASCADE)
    PROD_NOMBRE = models.CharField(max_length=50)
    PROD_DESCRIPCION = models.CharField(max_length=50, blank=True)
    PROD_SLUG = models.SlugField(max_length=250)
    CONTENIDO_PZS = models.CharField(max_length=50, blank=True)
    PROD_PRECIO_MAY = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    PROD_PRECIO_PUB = models.DecimalField(max_digits=10, decimal_places=2)
    PROD_DISPONIBLE = models.BooleanField(default=True)
    PROD_GRAMAJE = models.FloatField(null=True, blank=True)
    PROD_IMAGEN = models.ImageField(upload_to='productos/', null=True, blank=True)
    PROD_CREADO = models.DateTimeField(auto_now_add=True)
    PROD_MODIFICADO = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.PROD_NOMBRE
    
    def get_absolute_url(self):
        return reverse("productos:detalle_producto", kwargs={"id": self.id, "slug": self.PROD_SLUG})
    
    

cart/views.py
from django.shortcuts import render
from products.models import Producto
from .models import Cart, CartItem
from django.shortcuts import get_object_or_404
from django.views.decorators.http import require_POST
from django.http import JsonResponse
from django.shortcuts import redirect
# Create your views here.
@require_POST
def cart_add(request, product_id):
    cart_id = request.session.get('cart_id')
    
    if cart_id:
        try:
            cart = Cart.objects.get(id=cart_id)
        except Cart.DoesNotExist:
            cart = Cart.objects.create()
    else:
        cart = Cart.objects.create()
        request.session['cart_id'] = cart.id
        
    product = get_object_or_404(Producto, ID_PRODUCTO=product_id)
    category = product.PROD_CATEGORIA
    category_slug = category.CAT_SLUG
    cart_item, created = CartItem.objects.get_or_create(cart=cart, product=product)
    
    if not created:
        cart_item.quantity += 1
    cart_item.save()
    
    return redirect('products:product_detail', product_id=product_id)

def cart_detail(request):
    cart_id = request.session.get('cart_id')
    cart = None
    
    if cart_id:
            cart = get_object_or_404(Cart, id=cart_id)
    if not cart or not cart.items.exists():
            cart = None
    
    context = {
        'cart': cart,
    }
    
    return render(request, 'cart/detail.html', context)

def cart_remove(request, product_id):
    cart_id = request.session.get('cart_id')
    cart = get_object_or_404(Cart, id=cart_id)
    item = get_object_or_404(CartItem, cart=cart, product__ID_PRODUCTO=product_id)
    item.delete()
    
    return redirect('cart:cart_detail')


def cart_item_add(request, product_id):
    cart_id = request.session.get('cart_id')
    if not cart_id:
        return JsonResponse({'error': 'No cart found'}, status=404)
    
    cart = get_object_or_404(Cart, id=cart_id)
    product = get_object_or_404(Producto, ID_PRODUCTO=product_id)
    
    cart_item, created = CartItem.objects.get_or_create(cart=cart, product=product)
    
    if not created:
        cart_item.quantity += 1
    cart_item.save()
    
    return JsonResponse({'message': 'Item added to cart', 'quantity': cart_item.quantity})

def cart_item_remove(request, product_id):
    cart_id = request.session.get('cart_id')
    if not cart_id:
        return JsonResponse({'error': 'No cart found'}, status=404)
    
    cart_id = request.session.get('cart_id')
    if not cart_id:
        return JsonResponse({'error': 'No cart found'}, status=404)
    
    cart = get_object_or_404(Cart, id=cart_id)
    product = get_object_or_404(Producto, ID_PRODUCTO=product_id)
    
    cart_item, created = CartItem.objects.get_or_create(cart=cart, product=product)
    
    
    return JsonResponse({'message': 'Item removed from cart'})

products/views.py
from django.shortcuts import render, get_object_or_404
from .models import Categoria, Producto
from random import choice


def landing_page(request):
    template_name = 'products/index.html'
    lista_productos = Producto.objects.all()[:3]
    context = {
        "products": lista_productos,
    }
    return render(request, template_name, context)


def product_list(request, category_slug=None):
    category = None
    products = Producto.objects.filter(PROD_DISPONIBLE=True)
    categories = Categoria.objects.all()
    rand_cat = choice(categories)
    first_three = Producto.objects.filter(PROD_CATEGORIA=rand_cat)[:3]
    if category_slug:
        category = get_object_or_404(Categoria, CAT_SLUG=category_slug)
        products = products.filter(PROD_CATEGORIA=category)

    return render(request, 'products/product/list.html', context={
        'rand_cat': rand_cat,
        'category': category,
        'products': products,
        'categories': categories,
        'first_three': first_three
    })


def product_detail(request, id):
    product = get_object_or_404(Producto, ID_PRODUCTO=id, PROD_DISPONIBLE=True)
    categories = Categoria.objects.all()
    rand_cat = choice(categories)
    first_three = Producto.objects.filter(PROD_CATEGORIA=rand_cat)[:3]
    if not product:
        print("El Producto no fue encontrado")
    return render(request, 'products/product/detail.html', {'product': product, 'first_three': first_three, 'rand_cat': rand_cat, 'categories': categories})

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    {% load static %}
    <title>
      {% block title %}
        BioNutrex | Shop
      {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'dist/styles.css' %}" />
    {% block styles %}

    {% endblock %}
  </head>
  <body class="block">
    {% block banner %}

    {% endblock %}

    <header class="absolute top-0 left-0 w-full z-20">
      {% include 'includes/nav.html' %}
    </header>

    {% block carrito %}

    {% endblock %}

    {% block content %}

    {% endblock %}
    <footer>
      {% include 'includes/footer.html' %}
      <div class="container mx-auto p-4 text-center">
        <p class="text-gray-400">@2025 Quantum Code Ltd. Tdos los derechos reservados.</p>
      </div>
    </footer>
    {% block scriptsJS %}

    {% endblock %}
  </body>
</html>

templates/cart/detail.html
{% extends 'base.html' %} {% load static %} {% block title %}
  Mi Carrito | BioNutrex
{% endblock %}
{% block banner %}
  <section class="h-[72px]"></section>
{% endblock %}
{% block styles %}
  <style>
    .remove-btn {
      background-color: #dc2626 !important; /* Tailwind red-600 */
      color: #fff !important;
    }
  </style>
{% endblock %}
{% block carrito %}
  <div class="py-5 block" id="cartBlock">
    <div id="carrito" class="flex flex-col justify-center items-center w-full h-auto bg-[#1E1E1E] text-white top-10 left-10 transition-transform duration-300 transform">
      <div class="w-full h-20 flex justify-between items-start p-5 p-5 bg-[#1E1E1E]">
        <h2 class="text-lg font-semibold">Carrito de Compras</h2>
        <button id="closeCart" class="text-white hover:text-gray-400">X</button>
      </div>
      <div class="w-full h-auto max-h-[300px] overflow-y-auto p-5">
        <!-- Aquí se agregarán los productos dinámicamente -->
        {% if cart %}
          <ul class="space y-4">
            {% for item in cart.items.all %}
              <li class="items-center p-4">
                <div class="flex justify-between items-center mb-4 border-b border-gray-600 pb-2">
                  <span>{{ item.product.PROD_NOMBRE }}</span>
                  <span>{{ item.product.PROD_PRECIO_PUB }}</span>
                  <div class="flex items-center">
                    <!-- TODO: Hacer views de Sumar y Restar cantidad de producto en cart.views -->
                    <a href="#" class="bg-gray-800 text-white px-2 py-1 rounded">-</a>
                    <span class="mx-2">{{ item.quantity }}</span>
                    <a href="#" class="bg-gray-800 text-white px-2 py-1 rounded">+</a>
                  </div>
                  <a href="{% url 'cart:cart_remove' product_id=item.product.ID_PRODUCTO %}" class="px-2 py-1 rounded bg-red-500 text-white">Eliminar</a>
                </div>
              </li>
            {% endfor %}
          </ul>
        {% else %}
          <h1>El carrito está vacío</h1>
        {% endif %}
      </div>
      <!-- Contenedor para el total -->
      <div class="w-full px-5 py-3 bg-gray-800 flex justify-between items-center">
        <span class="text-lg font-semibold">Total:</span>
        <span id="totalPrice" class="text-lg font-semibold">$0.00</span>
      </div>
      <!-- Botón de checkout -->
      <button id="checkoutBtn" class="bg-green-500 text-white px-5 py-2 mt-3 rounded hover:bg-green-600 mb-5">Checkout</button>
    </div>
    <!-- carrito fin -->
  </div>

  <!-- TODO: TERMINAR EL CARRITO -->
  <!-- TODO: MANEJAR ADD Y REMOVE -->
  <!-- TODO: MANEJAR ELIMINAR PRODUCTO -->
  <!-- TODO: MANEJAR TOTAL DE COMPRA -->
  <!-- TODO: MANEJAR BLOQUE DESPLAZABLE : SEPARAR DETALLE DE CARRITO DEL BLOQUE DE CARRITO HTML -->
{% endblock %}

templates/includes/nav.html
{% load static %}
<nav class="container mx-auto p-4 w-screen h-13 relative flex justify-between items-center px-10 | lg:w-[80%] lg:mt-5 lg:rounded-4xl">
  <div class="title text-white text-lg relative z-10 flex | lg:flex-grow">
    <a href="{% url "products:landing_page" %}"><h1>BIO<b>NUTREX</b></h1></a>
  </div>
  <div class="menu hidden text-white text-lg relative z-10 flex justify-center items-center | lg:flex">
    <ul class="flex [&>li>a]:text-sm [&>li>a]:px-3 [&>li>a]:py-1 [&>li>a]:rounded-2xl [&>li>a]:hover:bg-[#686868] [&>li>a]:transition-all">
      <li>
        <a href="{% url "products:landing_page" %}#bestseller">Best Sellers</a>
      </li> <li>
        <a href="{% url "products:landing_page" %}">Home</a>
      </li>
      <li>
        <a href="{% url "products:product_list" %}">Suplementos</a>
      </li>
    </ul>
  </div>
  <div class="btns flex gap-2 relative z-10 [&>div>a>img]:w-6 [&>div>a>img]:invert flex flex-grow justify-end | lg:gap-5 lg:[&>div>a>img]:w-8">
    <div class="shopping-cart">
      <a href="{% url "cart:cart_detail" %}"><img src="{% static 'img/shop-cart.svg' %}" alt="Carrito" /></a>
    </div>
    <div class="browser">
      <a href=""><img src="{% static 'img/browse.svg' %}" alt="Buscar" /></a>
    </div>
    <div class="user">
      <a href="#"><img src="{% static 'img/user.svg' %}" alt="Perfil" /></a>
    </div>
    <div class="">
      <svg class="h-6 w-5 menu block lg:hidden" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
        <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
        <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g>
        <g id="SVGRepo_iconCarrier">
          <path d="M4 6H20M4 12H20M4 18H20" stroke="#ffffff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path>
        </g>
      </svg>
    </div>
  </div>
  <div class="absolute inset-0 bg-[#1E1E1E] opacity-50 rounded-inherit z-0 | lg:rounded-4xl lg"></div>
</nav>
<!-- TODO: Arreglar el menu nav mobile-->

templates/products/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  BIONUTREX - Fuerza en cada gramo
{% endblock %}

{% block banner %}
  <section class="h-screen bg-[url('/static/img/banner.jpg')] bg-cover bg-center bg-no-repeat">
    <div class="bottom-container h-full w-full flex flex-col justify-end items-center text-white px-5 pb-10 | lg:flex-row lg:items-end lg:justify-center lg:pb-10">
      <div class="flex text-center text-3xl font-bold | lg:w-[60%] lg:text-start lg:text-6xl">
        <h1>DESCUBRE LO MEJOR DE LA SUPLEMENTACIÓN</h1>
      </div>
      <div class="flex flex-col justify-end items-center text-center pb-10 [&>p]:text-lg [&>p]:mb-3 [&>a]:bg-[#FFFFFF] [&>a]:text-black [&>a]:rounded-3xl [&>a]:px-5 [&>a]:py-2 [&>a]:text-sm | lg:items-end lg:pb-0 lg:w-[40%] lg:text-end lg:[&>p]:text-2xl">
        <p>Mejores precios, alta calidad, compromiso con tu salud.</p>
        <a href="#">Comprar ahora</a>
      </div>
    </div>
  </section>
{% endblock %}

{% block content %}
  <!-- suplements start -->
  <section>
    <div class="suplements-container w-full mt-10 mb-10">
      <h4 class="text-3xl pl-5 | lg:text-2xl | 2xl:text-3xl">SUPLEMENTOS</h4>
      <div class="mt-10 suplements-section px-5 flex flex-col gap-5 | lg:flex-row lg:gap-5 lg:justify-center lg:items-center lg:w-full">
        <div class="protein h-[600px] bg-[url('/static/img/protein_section.jpg')] bg-cover bg-center bg-no-repeat flex flex-col justify-end items-center p-5 text-white | lg:flex-grow lg:items-start | 2xl:h-[800px]">
          <p class="pb-2 | lg:text-2xl">Proteína</p>
          <a class="bg-white text-black px-2 py-1 rounded-2xl" href="{% url 'products:product_list_by_category' category_slug='proteinas' %}">COMPRAR AHORA</a>
        </div>
        <div class="creatine h-[600px] bg-[url('/static/img/creatine_section.jpg')] bg-cover bg-center bg-no-repeat flex flex-col justify-end items-center p-5 text-white | lg:flex-grow lg:items-start | 2xl:h-[800px]">
          <p class="pb-2 | lg:text-2xl">Creatina</p>
          <a class="bg-white text-black px-2 py-1 rounded-2xl" href="#">COMPRAR AHORA</a>
        </div>
        <div class="Vitamin h-[600px] bg-[url('/static/img/vitamin_section.jpg')] bg-cover bg-center bg-no-repeat flex flex-col justify-end items-center p-5 text-white | lg:flex-grow lg:items-start | 2xl:h-[800px]">
          <p class="pb-2 | lg:text-2xl">Vitamina</p>
          <a class="bg-white text-black px-2 py-1 rounded-2xl" href="#">COMPRAR AHORA</a>
        </div>
      </div>
    </div>
  </section>
  <!-- Suplements end -->

  <!-- best seller inicio --> 
  <section id="bestseller" class="pb-10">
    <h4 class="text-3xl pl-5 lg:text-2xl 2xl:text-3xl">BEST SELLERS</h4>
    <div class="mt-6 px-5 grid gap-6 grid-cols-1 lg:grid-cols-3 justify-items-center">
      {% for product in products %}
        <div class="w-full max-w-sm">
          <img src="{% static 'img/prot-keto.png' %}" alt="" class="w-full" />
          <div class="flex mt-1">
            <h5 class="pr-2 py-1 text-lg lg:pr-1 xl:text-xl">{{ product.PROD_NOMBRE }} {{ product.PROD_GRAMAJE }}</h5>
            <a class="cursor-pointer bg-[#E0E0E0] text-black px-2 py-1 lg:px-1 lg:py-0 lg:text-[.7rem] lg:flex lg:items-center xl:px-2 xl:py-1 xl:text-[.9rem]" href="{% url 'products:product_detail' id=product.ID_PRODUCTO %} ">COMPRAR AHORA</a>
          </div>
        </div>
      {% endfor %}
    </div>
  </section>
  <!-- best seller fin -->
{% endblock %}

templates/products/product/detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  {{ product.PROD_NOMBRE }}
{% endblock %}
<!-- Boxicons here -->
{% block styles %}
  <link href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css" rel="stylesheet" />
{% endblock %}

{% block banner %}
  <section class="h-[72px]"></section>
{% endblock %}

{% block content %}
  <!-- btn return start -->
  <div class="flex items-center pl-5 pt-5 gap-2 | lg:gap-5">
    <div class="btn">
      <a href="{% url 'products:landing_page' %}"><img class="w-5" src="{% static 'img/arrow-left.svg' %}" alt="" /></a>
    </div>
    <div class="pb-1 pl-2">
      <a href="{% url 'products:landing_page' %}">Regresar</a>
    </div>
  </div>
  <!-- btn return end -->

  <!-- product detail start -->
  <div class="w-screen h-1/2 px-5 flex flex-col gap-5| lg:flex-row">
    <div class="left lg:w-1/2 flex flex-row justify-center items-center">
      <div class="p-5 justify-center items-center flex">
        <!-- Imagen de prod -->
        {% if product.PROD_IMAGEN %}
          <img src="{{ product.PROD_IMAGEN.url }}" alt="{{ product.PROD_NOMBRE }}" class="w-1/2 object-fill" />
        {% else %}
          <img src="{% static '/img/citrato.png' %}" alt="" />
        {% endif %}
      </div>
    </div>
    <div class="right lg:w-1/2 flex flex-col">
      <div class="p-5">
        <!-- Nombre del producto -->
        <h3 class="text-2xl | sm:text-4xl | md:text-5xl | lg:text-4xl">{{ product.PROD_NOMBRE }}</h3>
        <!-- Gramaje o contenid del producto -->
        <p class="text-md mt-1 | sm:text-lg | md:text-sm">{{ product.PROD_GRAMAJE }} mg</p>
        <!-- Descripción corta del producto -->
        <p class="text-md mt-1 | sm:text-lg | md:text-sm">{{ product.CONTENIDO_PZS }}</p>
        <div class="precio flex items-center gap-2 mt-5 mb-2">
          <!-- Precio del producto -->
          <p class="text-lg font-bold | sm:text-2xl |">${{ product.PROD_PRECIO_PUB }}</p>
        </div>
        <hr />
        <div class="w-full h-15 mt-5 flex gap-1 | sm:h-11 sm:gap-2">
          <!-- Add to shopping car btn -->
          <!-- Se desplegará carrito de compras -->
          <div class="w-full flex">
            <!-- Formulario para añadir al carrito -->
            <!-- TODO: Funcion para confirmar la adicion, slider del carrito hacia abajo. -->
            <form action="{% url 'cart:cart_add' product_id=product.ID_PRODUCTO %}" method="post" id="add-to-cart-form" class="w-full h-15 sm:h-11">
              {% csrf_token %}
              <button type="submit" class="w-full h-15 sm:h-11 bg-black flex justify-center items-center text-white transition hover:bg-[#686868] mb-2">Añadir al carrito</button>
            </form>
          </div>
        </div>
        <div class="w-full mt-2 flex">
          <!-- btn que dirigirá al checkout -->
          <!-- TODO: Boton que añade al carro y redirige a Stripe -->
          <form action="" method="post" class="w-full h-15 sm:h-11">
            {% csrf_token %}
            <button type="submit" class="w-full h-15 sm:h-11 bg-[#0D00BD] flex justify-center items-center text-white">Comprar ahora</button>
          </form>
        </div>

        <!-- acordion -->
        <div className="acordion-container ">
          <div class="accordion-header mt-10 flex items-center justify-between text-[#6D6D6D] cursor-pointer">
            <span class="font-semibold text-xl">Detalles</span>
            <i class="bx bx-chevron-down"></i>
          </div>
          <div class="accordion-body border-t-2 border-[#6D6D6D] max-h-0 overflow-hidden transition-all duration-200 ease-out">
            <div class="p-2 [&>ul>li]:text-[#6D6D6D]">
              <!-- Detalle de producto > Cada punto se pone dentro del "li" -->
              <ul>
                <li>Presentacion: {{ product.PROD_DESCRIPCION }}</li>
              </ul>
            </div>
          </div>
          <div class="accordion-header mt-10 flex items-center justify-between text-[#6D6D6D] cursor-pointer">
            <span class="font-semibold text-xl">Envíos</span>
            <i class="bx bx-chevron-down"></i>
          </div>
          <div class="accordion-body max-h-0 overflow-hidden transition-all duration-200 ease-out">
            <div class="p-2 [&>ul>li]:text-[#6D6D6D]">
              <ul></ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- product detail end -->
  <!-- Reseñas start -->
  <div class="reseñas-container w-screen px-5 mt-20">
    <p class="text-md text-[#6D6D6D] text-center">Reseñas</p>
    <h3 class="text-center text-xl font-semibold">Lo que nuestros usuarios dicen</h3>
    <!-- Reseña container > aqui se despliegan todas las reseñas -->
    <div class="slider-container mt-10 flex gap-2 lg:px-10">
      <!-- Reseña 1 -->
      <div class="reseña-card border-2 border-[#6D6D6D] w-full">
        <div class="content p-4 flex flex-col">
          <!-- Nombre cliente -->
          <h3>Luis venegas</h3>
          <p class="flex items-center gap-2">
            <!-- Calificacion cliente -->
            <i class="bx bxs-star"></i>4.5/5.0 Estrellas
          </p>
          <!-- Reseña cliente -->
          <p class="p-2">Reseña del cliente</p>
        </div>
      </div>
      <!-- Reseña 2 -->
      <div class="reseña-card hidden sm:flex border-2 border-[#6D6D6D] w-full">
        <div class="content p-4 flex flex-col">
          <h3>Luis venegas</h3>
          <p class="flex items-center gap-2">
            <i class="bx bxs-star"></i>4.5/5.0 Estrellas
          </p>
          <p class="p-2">Reseña del cliente</p>
        </div>
      </div>
      <!-- Reseña 3 -->
      <div class="reseña-card hidden xl:flex border-2 border-[#6D6D6D] w-full">
        <div class="content p-4 flex flex-col">
          <h3>Luis venegas</h3>
          <p class="flex items-center gap-2">
            <i class="bx bxs-star"></i>4.5/5.0 Estrellas
          </p>
          <p class="p-2">Reseña del cliente</p>
        </div>
      </div>
    </div>
  </div>

  <!-- Reseñas end -->
  <!-- Prod sugerencias start -->
  <div class="prod-sugerencias-container w-screen px-5 mt-20">
    <p class="text-md text-[#6D6D6D] text-center">Productos sugeridos</p>
    <h3 class="text-center text-xl font-semibold">Te puede interesar</h3>
    <div class="prod-suger mt-10 flex flex-col gap-2 items-center justify-center | lg:flex-row lg:gap-5 lg:px-10">
      {% for item in first_three %}
        <div class="w-full | sm:w-100">
          <a href="{% url 'products:product_detail' item.ID_PRODUCTO %}">
            <div class="content p-4 flex flex-col">
              <!-- Imagen producto -->
              <div class="border-2 border-[#6D6D6D] rounded-sm">
                <img src="{% static '/img/pre-workout.png' %}" alt="" />
              </div>
              <!-- Nombre producto -->
              <h3>{{ item.PROD_NOMBRE }} {{ item.PROD_GRAMAJE }}</h3>
              <!-- Precio producto -->
              <p class="text-lg font-bold">{{ item.PROD_PRECIO_PUB }}</p>
            </div>
          </a>
        </div>
      {% endfor %}
    </div>
  </div>
  <!-- Prod sugerencias end -->
{% endblock %}

{% block scriptsJS %}
  <script>
    document.getElementById('add-to-cart-form').addEventListener('submit', function (event) {
      event.preventDefault()
      const form = event.target
      const url = form.action
      const formData = new FormData(form)
      fetch(url, {
        method: 'POST',
        body: formData,
        headers: {
          'X-CSRFToken': formData.get('csrfmiddlewaretoken')
        }
      }).then((response) => response.json())
    })
  </script>

  <script>
    const accordionHeader = document.querySelectorAll('.accordion-header')
    accordionHeader.forEach((accordionHeader) => {
      accordionHeader.addEventListener('click', (event) => {
        accordionHeader.classList.toggle('active')
        const accordionBody = accordionHeader.nextElementSibling
        if (accordionHeader.classList.contains('active')) {
          accordionBody.style.maxHeight = accordionBody.scrollHeight + 'px'
        } else {
          accordionBody.style.maxHeight = 0
        }
      })
    })
  </script>
{% endblock %}